# Concat y append

In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'1.0.1'

In [7]:
# Precision a dos decimales a la libreria de python
pd.options.display.float_format='{:,.2f}'.format

In [8]:
# Precision a dos decimales a la libreria de numpy
np.set_printoptions(precision=2)

## Concatenación de matrices con numpy

In [13]:
# Generando dos matrices con valores aleatorios
x1 = np.random.rand(2, 5) * 100
x2 = np.random.rand(2, 5) * -10

In [16]:
x1, x2

(array([[95.61, 81.16, 63.9 , 20.29, 13.91],
        [79.14, 21.63, 66.02, 82.72, 51.63]]),
 array([[-2.17, -5.92, -7.66, -8.9 , -6.98],
        [-8.15, -1.64, -5.19, -8.97, -9.01]]))

In [19]:
# Concatenando las dos matrices
np.concatenate([x1, x2])

array([[95.61, 81.16, 63.9 , 20.29, 13.91],
       [79.14, 21.63, 66.02, 82.72, 51.63],
       [-2.17, -5.92, -7.66, -8.9 , -6.98],
       [-8.15, -1.64, -5.19, -8.97, -9.01]])

In [20]:
# Concatenando las dos matrices por columnas
np.concatenate([x1, x2], axis=1)

array([[95.61, 81.16, 63.9 , 20.29, 13.91, -2.17, -5.92, -7.66, -8.9 ,
        -6.98],
       [79.14, 21.63, 66.02, 82.72, 51.63, -8.15, -1.64, -5.19, -8.97,
        -9.01]])

## Concatenación de Series con pandas

In [23]:
s1 = pd.Series(x1[0], index=['a', 'b', 'c', 'd', 'e'])
s1

a   95.61
b   81.16
c   63.90
d   20.29
e   13.91
dtype: float64

In [24]:
s2 = pd.Series(x2[0], index=['c', 'd', 'e', 'f', 'g'])
s2

c   -2.17
d   -5.92
e   -7.66
f   -8.90
g   -6.98
dtype: float64

In [26]:
# Concatenando las dos series en filas
pd.concat([s1, s2])

a   95.61
b   81.16
c   63.90
d   20.29
e   13.91
c   -2.17
d   -5.92
e   -7.66
f   -8.90
g   -6.98
dtype: float64

In [27]:
# Concatenando las dos series por columnas
pd.concat([s1, s2], axis=1)

0     1
a 95.61   nan
b 81.16   nan
c 63.90 -2.17
d 20.29 -5.92
e 13.91 -7.66
f   nan -8.90
g   nan -6.98

In [31]:
# Si nuestro objetivo es concatenar dos series sin respetar el indice, debemos resetear el indice antes de realizar la concatenacion.
pd.concat([s1.reset_index(drop=True), s2.reset_index(drop=True)], axis=1)

0     1
0 95.61 -2.17
1 81.16 -5.92
2 63.90 -7.66
3 20.29 -8.90
4 13.91 -6.98

## Concatenación de dataframes con pandas

In [42]:
df1 = pd.DataFrame(np.random.rand(5, 2) * 100, columns=['a', 'b'], index=[1, 2, 3, 4, 5])
df1

a     b
1 45.58 72.92
2  5.82  8.45
3 23.62 45.29
4 35.87 58.59
5 33.62 64.78

In [43]:
df2 = pd.DataFrame(np.random.rand(5, 2) * -1, columns=['a', 'b'], index=[5, 6, 7, 8, 9])
df2

a     b
5 -0.02 -0.65
6 -0.19 -0.18
7 -0.96 -0.39
8 -0.89 -0.38
9 -0.68 -0.96

In [44]:
# Concatenando los dos dataframe
pd.concat([df1, df2])

a     b
1 45.58 72.92
2  5.82  8.45
3 23.62 45.29
4 35.87 58.59
5 33.62 64.78
5 -0.02 -0.65
6 -0.19 -0.18
7 -0.96 -0.39
8 -0.89 -0.38
9 -0.68 -0.96

In [45]:
# Concatenando los dos dataframe a lo largo de la columna
pd.concat([df1, df2], axis=1)

a     b     a     b
1 45.58 72.92   nan   nan
2  5.82  8.45   nan   nan
3 23.62 45.29   nan   nan
4 35.87 58.59   nan   nan
5 33.62 64.78 -0.02 -0.65
6   nan   nan -0.19 -0.18
7   nan   nan -0.96 -0.39
8   nan   nan -0.89 -0.38
9   nan   nan -0.68 -0.96

In [48]:
# Si lo que deceamos es concatenar los elementos que comparten el indice lo podemos hacer utilizando el atributo join.
pd.concat([df1, df2], axis=1, join='inner')

a     b     a     b
5 33.62 64.78 -0.02 -0.65

In [49]:
# Podemos concatenar dos dataframe y no respetar sus indices
pd.concat([df1.reset_index(drop=True), df2.reset_index(drop=True)], axis=1)

a     b     a     b
0 45.58 72.92 -0.02 -0.65
1  5.82  8.45 -0.19 -0.18
2 23.62 45.29 -0.96 -0.39
3 35.87 58.59 -0.89 -0.38
4 33.62 64.78 -0.68 -0.96

## Unir dos DataFrame utilizando append

In [51]:
# Uniendo los DataFrame a lo largo de las filas
df1.append(df2)

a     b
1 45.58 72.92
2  5.82  8.45
3 23.62 45.29
4 35.87 58.59
5 33.62 64.78
5 -0.02 -0.65
6 -0.19 -0.18
7 -0.96 -0.39
8 -0.89 -0.38
9 -0.68 -0.96

In [54]:
# Uniendo dos DataFrame a lo largo de las columnas utilizando la transpuesta
df1.T.append(df2.T).T

a     b     a     b
1 45.58 72.92   nan   nan
2  5.82  8.45   nan   nan
3 23.62 45.29   nan   nan
4 35.87 58.59   nan   nan
5 33.62 64.78 -0.02 -0.65
6   nan   nan -0.19 -0.18
7   nan   nan -0.96 -0.39
8   nan   nan -0.89 -0.38
9   nan   nan -0.68 -0.96